keshav_chats = [
  "Hello roomies",
  "Gali de chuka!",
  "🥺",
  "Merko bhi krni padi.... Ase pakad kr khada rha!",
  "Bss chup chap smile krta rha;",
  "Aur bhai abhi toota toh 16000 jaenge",
  "Toh smbhalna hain hme!",
  "Bss kuch din!",
  "Todna zaroori hain?",
  "Haan whi!",
  "Rahul ab main 2nd number ka Banda bn gya?",
  "1st?",
  "🌈🌈",
  "Heyy!!! Rommieee",
  "<Media omitted>",
  "@⁨Meta AI⁩ create a image that depicts \"I have a proof now\"",
  "Lord himanshu lord Rahul and lord harsh",
  "Nice",
  "@⁨Kartik Cse⁩ Kartik Get ready bro",
  "main toh hu hi",
  "@⁨Meta AI⁩ kru use?",
  "rahul yeh pic use krlu?",
  "ya tu kr rha?",
  "haan tu tyari kr",
  "dnd",
  "chup hoja chup hpja",
  "haan",
  "sbme dena hain",
  "it is like satta",
  "khelo bss",
  "HOmie HOmies suno",
  "the topic of for ppt is ANY LATEST TECHNOLOGY LIKE BLOCK CHAIN TOO",
  "sirf AI topic nhi hain",
  "tu randike form bhar",
  "essay me position chiaye",
  "haan",
  "sb kuch krde",
  "mane toh sbme bhara hain",
  "bhai yeh ek satta hain bina paso ka",
  "chup chap khelo",
  "is satte me haar nhi hain",
  "sirf jeet hain ya seekh hain",
  "<Media omitted>",
  "I am quiz (if I get the team), Declamation, ppt(akele hi krunga)",
  "aaja na tu bhi",
  "bakchodi na kr",
  "khula pasa bat rha hain",
  "essay me aajaegi position",
  "baat maan",
  "randike terse hota kya hian siway DSA ke",
  "yeh bhi nhi hota woh bhi nhi hota",
  "harsh chauhan tk kr rha hain",
  "aaja na",
  "phir nhi krenge kuch bhi",
  "Homies quiz me toh hain nahum?",
  "<Media omitted>",
  "bhai m lib hu",
  "iss OBC room wale ko pada rhne de",
  "hum original 3 + 4th member harsh ko kr lenge",
  ".",
  "pakka hain",
  "+ chakkam chakka",
  "kartik aajao please🥹",
  "sun toh tu essay me liyo",
  "aur kisi 3sre me bhi",
  "bc le de ke 3rd toh aae",
  "haan kyu nhi de bhai",
  "interview me kaam aaega",
  "chut kbhi na kbhi toh marega hi",
  "ab m nhi kr rha motivate",
  "aur kartik quiz me meri maane toh alag team bna le",
  "sakshi se puchle",
  "iss se 2 proces ho jaenge",
  "positions",
  "nhi",
  "i am thing ki kartik sakshi ujjwal aur koi bhi ek au rteam bna ke",
  "le",
  "hum iss topic pr raat ko meeting krenge",
  "at 9 PM",
  ".",
  "are tu sakshi ujjwal aur 4th person team bna lo",
  "taki 3 me 2 position hmari ho",
  "haan",
  "chup reh tu",
  "ek team me 2 intelligent kalesh hi machate hain",
  "hmari team ka coordination ach ahin",
  "room no .29 is best",
  "haan",
  "aur tu sakshi se baat krle",
  "haan m krta hu",
  "haan",
  "byee",
  "okay",
  "kartik ppt bhi bna le",
  "agr na bne toh mujhe bta m deta hu",
  "ok",
  "yeeeaahaahahahhaahahhaah",
  "what else you need",
  "@⁨Rahul Singh New⁩ Do your best in ppt ander se khabar mili hain ki badi badi hastiya participate kr rhi hain",
  "Kon ?",
  "Keshav Kumar Anshu Tiwari Nidhi types",
  "yeh bkl bolne me tej hain",
  "Rahul ke nudes are better",
  "bkc rola kr denge rahul ke me",
  "sbki",
  "haan",
  "pta nhi",
  "randiyo ka yhi hain bhai",
  "kuch nhi kr skte",
  "ok",
  "Join me",
  "Hello everyone , as we know we are participating in this event here I am telling you the participants from our grp",
  "<Media omitted>",
  "Quiz:- 1.Himanshu\n           2.Rahul\n           3. Keshav\n           4. Harsh",
  "Poster: 1. Himanshu",
  "Ppt : Rahul\n         Keshav",
  "Declaration Keshav kartik harsh",
  "Essay Harsh Kartik",
  "Himanshu essay me aaja",
  "*Suno sbhi apne apne 2/3 events bhejo*",
  "koi bhis sunny ki video pr react mt krna",
  "Sutro ke hawale se khabar mili hain ki...\nQuiz Priyanka aur Neha(ME) wali bna rhi h",
  "Don't leak it",
  "Guys Priyanka is chemistry teacher we have to be extra prepared",
  "Wait",
  "😂😂",
  "nyu laadle nyu",
  "cutu aapka topic kya tha",
  "@⁨Kartik Cse⁩  \n---**Introduction:**  \n\"Good morning, everyone! Today, we are going to talk about **semiconductors**—one of the most important materials in modern technology. \n\n---\n\n**Topic 1: What is a Semiconductor?**  \n\"A **semiconductor** is a material that can conduct electricity, but only under certain conditions. This makes it different from **conductors** like copper, which always conduct electricity, and **insulators** like rubber, which never conduct electricity.\n\nThe most common material used to make semiconductors is **silicon**. In its pure form, silicon doesn’t conduct electricity very well. But when we add small amounts of other materials to it, like phosphorus or boron, we can control how well it conducts electricity. This process is called **doping**.\"\n\n---\n\n**Topic 2: How Semiconductors Work in Electronics:**  \n\"Semiconductors are the building blocks of almost all modern electronic devices. Inside your phone or computer, there are millions of tiny semiconductor components that control the flow of electricity.\n\nOne of the most important semiconductor components is the **transistor**. A transistor acts like a switch—it can turn the flow of electricity on or off. This is how your computer’s processor works: millions of transistors switch on and off, processing information at incredibly fast speeds.\n\nSemiconductors also form the basis of **diodes**, which allow electricity to flow in only one direction. This is very important in controlling the flow of electricity in circuits.\"\n\n---\n\n**Topic 3: Types of Semiconductors:**\n\n\"Semiconductors can be divided into two main types:\n\n1. **n-type semiconductor**: In this type, extra electrons are added. These electrons are negatively charged and move easily, allowing the material to conduct electricity.\n  \n2. **p-type semiconductor**: In this type, there are **holes** where electrons should be. These holes are like empty spaces that can move around, and they act as positive charges.\n\nWhen you combine **n-type** and **p-type semiconductors**, you get what’s called a **p-n junction**. This junction is the heart of many electronic components, like **LEDs** and **solar cells**.\"\n\n---\n\n**Topic 4: Importance of Semiconductors in Modern Technology:**  \n\"Semiconductors are everywhere in modern technology. They are in **microchips**, which are the brains of your computers, phones, and even cars. Without semiconductors, we wouldn’t have the fast, powerful, and small electronic devices that we use today.\n\nIn addition to computers and phones, semiconductors are used in:\n\n- **Solar panels**: Semiconductors in solar cells convert sunlight into electricity.\n- **LED lights**: Semiconductors help make LED lights energy-efficient and long-lasting.\n- **Medical devices**: Semiconductors are used in many medical machines, from MRI scanners to heart rate monitors.\"\n\n---\n\n**Topic 5: Future of Semiconductors:**  \n\"What’s the future of semiconductors? As technology advances, we need faster and more efficient semiconductors to handle the increasing demands of modern electronics.\n\nOne exciting development is the use of **nanotechnology** to create **smaller and more powerful transistors**. This allows companies to make devices like smartphones and computers faster and more efficient.\n\nAnother development is **quantum computing**, where researchers are trying to use semiconductors to build computers that can solve problems much faster than today’s computers. This could change industries like healthcare, finance, and artificial intelligence.\"\n\n---\n\n**Conclusion:**  \n\"In conclusion, semiconductors are the backbone of modern technology. They make it possible for us to have the fast, powerful, and smart devices we use every day. As we continue to innovate and improve semiconductor technology, we can expect even more amazing advances in the future.\n\nThank you for your attention, and I hope you now have a better understanding of what semiconductors are and why they are so important in today’s world. Let’s keep learning and pushing the limits of what technology can do!\"\n\n---",
  "hum how to fuck money pr bole?",
  "btaiyo 20+ rs kase use krte hian",
  "tu kartik randike tameez sikhle milte hi padhne lg gya kuch reply toh det ehain",
  "Rahul ppt how is it going on",
  "make it on a futuristic theme like green color",
  "chod du stage pr pehkr nidhi bajeli ko",
  "suna headphone walo ko deti hain",
  "Baje gi*",
  "dr. doom jesa",
  "woh mne krli",
  "teri theme dikahiyo",
  "ok",
  "fucking genius my boy",
  "asi agr tune atleast 5 slides krdi na bhai 1st price tera hain bss bol thoda thik se liyo",
  "ruk m meri share krta hu",
  "This message was deleted",
  "Yeh gaand se bhi dikaega kuch?",
  "Nhi yaar m nhi dikhara Rahul ki zyada achi hain!",
  "Mane sharam aari hain!",
  "@⁨Rahul Singh New⁩ laptop leke aaega?",
  "?",
  "?",
  "😂😂",
  "sun hmari better hain content iska bada bhi hain in short hmare opponent ban rhe hain asi ppts",
  "haan mne bhi liya hain",
  "https://www.instagram.com/reel/C_FKGygx5o4/?igsh=azZuZnZzdTk1d3Jz",
  "Bc ppt kitni % ho gyi?",
  "Ok",
  "sirf 2 hr pehle isne 15+ Q kr diye",
  "bc padhne me bhi toh time lgta hain code likne me bhi",
  "<Video note omitted>",
  "Paso ki investment ki tyari kr rha",
  "Haan",
  "Relaay",
  "Declamation m 13 entries \nScience quiz m 43 entries \nPoster m 23 entries",
  "yeh bda ganda khel hone wala hain",
  "aur @⁨Rahul Singh New⁩  Ankit Bihari and Simran Bahdurgarhan are participatinh",
  "in PPT",
  "SO prepare well speaking too",
  "hum dino milkr total 1800 laenge",
  "jase bhi lae",
  "bhai logic me dikkat ho jaegi smjh",
  "m krwaunga practice",
  "@⁨Rahul Singh New⁩ mujhe nhi pta jo bhi kro kase bhi kro kal tk mujhe explanation tyar chaiye",
  "again I don't care terko jo such suwidhae madad ......... khud bill gates chaiye toh woh bhi",
  "sb milega but I want your ppt to be best and speech too",
  "haan",
  "in namuno ne",
  "4 krdi entry",
  "inn namuno ke kartik ki team included hain",
  "haan",
  "aur ise hmari tean ko fateh hasil krnu hain mtlb krni hain",
  "@⁨Himanshu Sharma⁩ Please be ready forget your introvertness and try to find good posters and '",
  "3 ko gaama ai wali m de chuka",
  "Also stay active during quiz",
  "naam hona chiaye hamara",
  "@⁨Himanshu Sharma⁩ ..... please reply",
  "where r u?",
  "mafia mundeer naam rakhle hum grp ka???....... nhi tut jaega",
  "HRK ARMY",
  "hawasi darinde",
  "@⁨Harsh Fbd EE⁩ @⁨Rahul Singh New⁩ @⁨Himanshu Sharma⁩  there will be a team meeting at 9PM",
  "sbse Pehle naam unka hi hain",
  "@⁨Himanshu Sharma⁩ Please respond my dear",
  "Kal lgegi pta aaj woh punima randi chutti pr hain",
  "@⁨Rahul Singh New⁩ @⁨Himanshu Sharma⁩ .... bhai ko bol ki preparation tagli krde heavy competition hain",
  "yeh bhai",
  "aur thodi chemistry smbhal liya",
  "liyo",
  "<Media omitted>",
  "<Media omitted>",
  "@⁨Meta AI⁩  Write a apprediation message to my griend that he is doing awesome and keep it up best of leck for his competition",
  "@⁨Meta AI⁩ friend name is Rahul and my name is Keshav",
  "@⁨Meta AI⁩ @⁨Rahul Singh New⁩",
  "vipaksh majboot hain mitra iss duryodhan ko apne karn ki need hian",
  "i mean arjun ko krishna ki",
  "Simran's most advanced version's ppt",
  "it's awesome",
  "but sbhi yhi bolenge😂😂",
  "genuinely padh liya bhai isko ache se padhle",
  "aur yaad krle",
  "style me boliyo",
  "baki baatein meeing at 9",
  "Haan mane mane terko bola bhi tha",
  "nut yeh best thi",
  "but*",
  "suo h kya yeh?",
  "duo*",
  "Ok age ki baat hogi 9 bje",
  "thik hian",
  "bhale single single aajae",
  "duo aajae",
  "yeh 1800 toh hmare hi hain",
  "bilkul",
  "cheque toh hum hi lenge",
  "Rahul tu koi gaana soch",
  "entry pt",
  "Startiing me dal le",
  "Prize lete time",
  "hm jana cancel krde?",
  "bhaiyo jb tk haar nhi jate tb tk man kr chalo jeet hmari hogi",
  "9 bje milte h",
  "DEclamation\n\n1. shruti prasad\n2. Varun kumar\n3. nidhi bajeli\n4. sapna mohanta\n5. harsh kumar\n6. keshav sharma\n7. karan\n8. kartik garg\n9. ajay kumar\n10. anshu tiwari\n11. harshit kumar\n12. simran \n13. himanshu mishra\n14. muskaan",
  "bhaiyo bahut heavy competition hain",
  "yeh sequence nhi hain sequence apne hisaab se bnaenge",
  "man toh mera bahut kuch krta hain",
  "are dekhte hain",
  "main krunga krunga kuch algorithm",
  "oe kartik cod elikh bkl",
  "@⁨Rahul Singh New⁩ ppt me bahut entry hain bhia",
  "tyari krle",
  "ok",
  "<Media omitted>",
  "<Media omitted>",
  "@⁨Himanshu Sharma⁩",
  "Haan hme kuch beech me jvgad",
  "Jugaad krna hoga",
  "But fir Tera aur mera saath ho jaega",
  "Rahul should we risk giving them our PPT?",
  "Kr toh rkhi h",
  "hum 3no hain .... aur tu iklota member",
  "Everyone best of luck",
  "Specially @⁨Kartik Cse⁩ @⁨Rahul Singh New⁩ ..\n\nAs it's your first time rock krdena bhaiyo",
  "@⁨Himanshu Sharma⁩ agr m late ho jau toh quiz me chale jana *best of luck for that*",
  "haan just in case",
  "ok",
  "ok",
  "Main hu bhai",
  "As quiz me leader ko hi jana hian!",
  "Screening test",
  "😂😂",
  "@⁨Kartik Cse⁩ bhai tu hme best of luck nhi bole?",
  "<Media omitted>",
  "😂",
  ".",
  ".",
  "Rewari*",
  "This is not for what my friend have given his 6 precious days",
  "Wake up",
  "Bhaiyo aajao",
  "M screen ling me baith gya",
  "Himanshu woh speech iot wali le aa",
  "Kal aajaiyo",
  "Bua ko pareshaan kr rha",
  "Haan",
  "Ab dsa se phele uski tyari kro",
  "😂😂",
  "Rahul aaja 🥺",
  "Clg aaja",
  "Himanshu ko cheers krenge poster me",
  "Yaad kyu Krna hain!",
  "Viva h yeh?",
  "Tbhi rukna tha na",
  "Yeh jakham kase bharenge",
  "Tauuuuu",
  "Kal mishra aaya room me puchta keshav ruk rha h",
  "M yhi hu tu aaja",
  "Himanshu ke liye cheers Krna hain",
  "Aaj aaja",
  "M toh aaj nikal jaunga",
  "At any cost",
  "Neha malik samne baithi thi aur asked ki kyu muskura rhe hon",
  "Dikha du?",
  "Himanshu ko dunga",
  "Legi toh lelegi",
  "Warna mane bol diya ki dediyon kisiko",
  "Harsh papa ka naam bta",
  "Ruko",
  "https://docs.google.com/forms/d/e/1FAIpQLScPEAFbhoIIZgnpdT-toIU0m-S0mbvuShNRGJXApTfsJ07EBQ/viewform?pli=1",
  "Kartik tera mane kr diya",
  "Tu Mt bhariyo",
  "Baki apni team ke teeno members bharfo",
  "Haan",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "Nothing phone 2",
  "Himashu ke liye extra prize krwa fiya",
  "Mtlb appreciation",
  "Ki yeh 3rd wale just hi niche the",
  "😂😂",
  "Apna woh reel yaad hain your brain reader\nenter a number ...x\n\nAnalysing your brain readin mind waves reading eyes measuring head beats...\n\nThe number in your brian is x",
  "Pehle yeh bta tu yeh vidoe kyu dekh rha tha tere paas voterid card bhi nhi h",
  "Aur woh sitthhu bhi",
  "<Media omitted>",
  "@⁨Kartik Cse⁩",
  "😂😂😂",
  "Tu abhi so ... 5 bje uth skta h",
  "Ase hi jeewan ke maze h bhai",
  "Ek life h usme yeh winter arc ku bakchodi",
  "Venkat Rammna Govinda mere dosto",
  "🙌🙌",
  "Blueprint tyar kro",
  "Kyuki kya pta hum saath me quiz na jeet skte ho aur dhandha kr skte ho",
  "Mard h bhai cheat toh Krna hi chaoye",
  "<Media omitted>",
  "Bc yeh clg walo ko kitni last date deni hoti h!!.... Agr woh last date nhi thi toh uss din hi na submit krwadete hum log",
  "@⁨Kartik Cse⁩ chale kya?",
  "Kya ase buss pass bn jaefa?",
  "<Media omitted>",
  "yeh chauhan ne BJP ko vote diya h na",
  "haan bhai",
  "1500 ka 10% is 150 1500+150=1650",
  "Enjoy",
  "masala btech se kam hain",
  "bhai mere paas jo news aayi mane bta di",
  "bhai tu bss vote mt diya kr",
  "*Greetings!*\n\nWe are pleased to inform you that the CRSSIET’s CSE Coding Club, DIGITRON, is once again with us. We are here to foster exploration and growth in our shared knowledge and skills. The primary goal of our club is to equip members with high-quality skills through various events and activities, encouraging broad participation.\n\nWe are excited to announce the designations for the DIGITRON Club for the year 2024:\n\n • *President* Keshav Kumar (4th year)\n• *Vice President* : Anshu Tiwari (4th year)\n• *Secretary* : Ravinder Tyagi (4th year)\n• *Joint Secretary* : Sapna (3rd year)\n• *Programming Head (Male)*: Rishi Yadav (2nd year)\n• *Programming Head (Female)*: Sneha Kukrety (4th year)\n• *Graphic and Media Head* : Vighnesh (3rd year)\n• *Graphic and Media Coordinator* : Mayank (2nd year)⁠\n• *Technical Head* : Raman Lamba (4th year)\n• *Technical Coordinator* : Ashwani Kumar (2nd year)\n• *Technical Coordinator* : Himanshu Mishra (2nd year)\n• *Finance and Planning Head*: Krishan Kaushik (4th year)\n• *Finance and Planning Coordinator* : Hanish (2nd year)\n• *Finance and Planning Coordinator* : Rishabh (2nd year)\n• *Executive Head* : Prabhat Kumar (2nd year)\n• *Event Head* : Kiran (4th year)\n• *Event Organizer* : Varun Kumar (3rd year)\n• *Event Coordinator* : Harshit (2nd year)\n• *Event Coordinator* : Ritu (1st year)\n\nWe look forward to your active participation and support.\n\n*Best regards*,\nDIGITRON Club",
  "@⁨Kartik Cse⁩ be like inn sbko ek saath coding me chodne ka lund rakhta hu",
  "Haan",
  "Haan asa kro digitron join krlo",
  "Pehle kuch krlebhai phir gyaan chodiyo",
  "Okay",
  "M bhi kuch nhi bolunga",
  "Haan bhai @⁨Kartik Cse⁩ chale",
  "@⁨Harsh Fbd EE⁩  ko Mt btana",
  "Kyuki woh bhramin tha 😁",
  "Uske paas baniya mitra bhi nhi tha yeh bhi thi ek baat",
  "Kya hmne BJP jaisi capitalistic govt ko vote dekr theek kiya?... Jisne aate h fees badha di?",
  "M kahunga ..... Haan!!!... Jb re ke form bhrenge toh socho hmara kitna naam hoga",
  "https://youtu.be/7ptRPKcQQis?feature=shared",
  "Le keshav",
  "Script yhi se yhi thi",
  "Gyi*",
  "Diwali mela pr saari beetches pr try krenge last event h",
  "Tb tk hmari placement ho chuki hogi bitches hm or try maregi",
  "Hmare yha gandi shakal walo ko hi mr./miss fresher bnate h kya?....\n\nSuppose yeh msg m unofficial me likhdo",
  "Iska vote nhi bhai permission lgegi",
  "Goldy brar(zimmedari lega)",
  "But agr yeh na ho paya toh \n2nd priority is Room joki harsh ki zimmedari hain\n\nAnd 3rd priority is PG",
  "8k me badhiya milra ho sector me toh chalega?",
  "Are bhai chup hoja tu",
  "Lele toh",
  "Tera kaam h hm jitne bole utne pase dedena",
  "Haan toh mane mane varun ko bola h woh dekh rha h",
  "Tu harsh chauhan so mat mujhe list chaiye room+ facilties+ kiraya+ distance from bus iski ek excel sheet chaiye",
  "Ok",
  "Kaash hum pehle hi lelete",
  "Hme hostel me rehna padta",
  "Haan",
  "Jisko jo Krna h wase kro",
  "Haaayeyeyeye 🥰",
  "Washroom price?.... Price in extreme summers?",
  "😂😂",
  "😂😂",
  "Delhi h yeh",
  "Aur ghar dekhne ki need nhi h jitna sasta ho ske utna acha h!",
  "No issues",
  "Tu abhi krde m baad me kr dunga",
  "Haan",
  "Tu uska QR code bhej diyo",
  "Bc kase dost h hum ek dusre pr ek pase ka bharosa nhi hain 😂😂😂",
  "QR code bhejiyo",
  "Bhai tu kyu jaega jhajjar",
  "Ek kaam kr dekh kr aa agr hmne kiye toh huk dedenge kiraya",
  "Rhne do",
  "Haan bhai hm nhi dere tujhe pase",
  "Exactly 💯",
  "Tum bc bina chokidari krte Ek din aur agle din pase lene aajate",
  "Mkc",
  "734 rs kon dega?",
  "Ok",
  "Tune apne 20 rs ke redi wale purse ka randi rona nhi choda hum kiwi ka hi flex na kre",
  "Iss kartik ka room me koi contribution nhi hain ..... \n\nMane alumni network se contact Kiya \nTum dono ghume .... 734 rs toh kartik hi dega",
  "Kartik thodi hu!",
  "Yaar koi jakr payment kr aao room me shift diwali ke baad ho jaenge 7 8 nov tk taki hum Jan me bhi thode din reh pae",
  "Unko call kr ke confirm krlo",
  "Ki haan hum hi lenge",
  "Haan",
  "Toh rahul agr aap jaoge toh meri taraf se 50 rs ki cheezi aapko!",
  "@⁨Harsh Fbd EE⁩ please confirm 2200 wala room",
  "Haan kro",
  "@⁨Kartik Cse⁩ hoja bhai",
  "Yeh room jaisi cheeze ase hi hoti h",
  "Haan yeh dega hme maa behen ki gali",
  "M krta hu baat",
  "Bhai woh aunty ke ghar rehte woh hme khana bhi khilati",
  "bhai use kh dena switches shi krva le please !",
  "Nhi yaar krni hain!",
  "Nahi mari bhai m fasa hua hu!n",
  "Koi nikalo toh m baat kru",
  "<Media omitted>",
  "Aur mne tera comment dekh kr",
  "Aur ab ek round aur marunga",
  "Room pr discuss kre?",
  "Bonjour",
  "Same hua h bhai literally bss hizru nhi bola",
  "Bhai Mujhe 3000 wale me nahi rehna 2200 wale me rehna h",
  "Chalo ab iss Baat bs behes krte h",
  "Sbhi homies aur homies ki family hmari family ki taraf se  Dhanteras ke tyohar ki hardik shubhkamnaye ....\n\nDevi Laxmi and kuber aapke ghar pr kabza kele.... Aur aapko aapaar sampatti ki prapti ho asi aasha krta hu",
  "Sbhi homies aur homies ki family hmari family ki taraf se  🎇 🪔 ke tyohar ki hardik shubhkamnaye ....\n\nDevi Laxmi and kuber aapke ghar pr kabza kele.... Aur aapko aapaar sampatti ki prapti ho asi aasha krta hu",
  "Haan toh?",
  "Chauhan tu priority list me uper hota jaa rha hain!",
  "@⁨Rahul Singh New⁩ yeh mulle aakr Teri gaand me tabahi machenge na tb smjh aaega",
  "Tu kuch bhi kr aaj sb maaf hain",
  "Are tu negative me tha time lgega",
  "M bhi phodta hu bc ek toh chinta samaj ke ghar",
  "Bhai Inka ek chota sa bacha merse puchta ki bhaiya mere gharwale kyu nhi mna rhe",
  "Aaj haryana diwas hain bihariyo ko mare?",
  "Fir jai haryana bhi bulwaenge!",
  "11:57 pr",
  "Bcz I'm ready",
  "<Media omitted>",
  "Agr hmare room pr aaya toh hum kya krenge ? Thakur in both forms",
  "Whi h bhai advanta hospital aur konsa school tha uss wali gali me h bhar bhar ke",
  "Aur aaj dekhiya koi better lge toh thik h warna woh Anil wala confirm krdo",
  "Tu ek pahuch Jaa phir krwa denge",
  "Call pr seedha uske account me",
  "M bolra hu 2500 wala krdo woh bhi chala jaega",
  "Toh tu 4k ke ander room doondh de",
  "Please rahul 🙏",
  "Haan krdo guys",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "Yeh aunty ka hain?",
  "Ya member ka?",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "@⁨Harsh Fbd EE⁩ @⁨Kartik Cse⁩ \n\n\nTum dono bkl room jaisi imp cheez ko serious nhi lete ho please mazak Mt kro ..... M sach m bimar hu kabhi bhi dr. Ke jane ki new ho jati hain warna m aa jata m uss din bhi bol rha tha ...\n\nPlease kal jao aur room fix krdo .... Maxm budget is 1500/head..... Please dhund lo!!!",
  "@⁨Rahul Singh New⁩ .... Please help us out in this",
  "Aur bhai ase hi krte rhoge toh end of he hme pg ya hostel me rehna hoga aur woh mujh bimari ke liye nhi hoga thik!",
  "@⁨Kartik Cse⁩ .... Terse yeh umeed nhi thi ki tu nhi smjhega Bhai m smjh rha hu ki tu chah rha hain ki m bag uthau aur mujhe pta hi kha Jana hain kha hain kmra but yeh itna aasan nhi hain .... Hme Krna padega room ...\n\n\nAur please yeh Mt bolna ki tujhe kuch nhi hora agr tu yeh bolra h toh yhi sochiye tu apne papa ke liye nhi yhi bolra hain kyuki bhai hain sach me dikkat",
  "@⁨Harsh Fbd EE⁩ @⁨Rahul Singh New⁩ ...\n\nBhai yeh kartik toh nhi smjhega please tum dono kal jakr room fix krdo",
  "Fir isko room me rhega na toh taane maarenge ki tune room ke liye hi kya hain tu nikal?",
  "Hana and the people who will help us out in getting a room will get a chakam chakka(upto rs100 + amt stole from @⁨Kartik Cse⁩ )",
  "Okay",
  "Main nhi woh ghanshyam doctor",
  "Ruk 500 aur mangne de",
  "@⁨Harsh Fbd EE⁩ @⁨Rahul Singh New⁩   tum dono ke 333 333 konse QR code pr bhejne h?",
  "Yeh hass kyu rha h isko rula",
  "Kartik wale krdu?",
  "Room pr Sara hisaab ktlr lenge",
  "<Media omitted>",
  "Any update on room?",
  "@⁨Harsh Fbd EE⁩",
  "Any update",
  "?",
  "Aur hum kal hi shift ho jae?",
  "Okay @⁨Kartik Cse⁩ kal apna sara saara saaman lekr aajana",
  "Hum log phele dhoondhege aur usi time pase dekr shift ho jaenge",
  "Where is percentage option?",
  "Pehle kal Milne ki jagah aur time confirm krlo!",
  "Bag kha rakhenge?",
  "Tu bsdk lugai hi hain isko toh chodenge",
  "Kisi din kartik se man bhar jaega toh!",
  "Bhai yeh toh nhi kr rha kam",
  "Bolra ki Mane minimum hi btaya h",
  "Room book hote hi btana",
  "Ok",
  "Wase yeh toh mere paas hi nhi h tere paas aaya kha se",
  "Bhai but yha agr zyada log rhne lg gye na",
  "Toh hostel wali hi vibe reh jaegi",
  "Bilkul bhaichara zyada Mt Krna",
  "Kisi chutiye se toh bilkul bhi nhi",
  "Bhaiyo list bnalo reliance mega Mart se hi lenge sasta bhi padega",
  "Rahul ke paas card bhi h",
  "Woh membership card jo tu bolra tha",
  "Ki mne bnwaya hain!",
  "Thik h nhi bhi h toh still whi se lenge",
  "Ek baat btao hum 4th person ko jb man chahe rakh skte h?",
  "Bina kisi price increase eke?",
  "Handwash*",
  "@⁨Harsh Fbd EE⁩ @⁨Rahul Singh New⁩  agr tum kartik ko iss halat me chod kr gye na toh dost chodo tum mard mard bhi chodo insaan bhi nhi ho",
  "Main sharabi dedunga",
  "Sharap dedunga agar tum usko akele chod kr gye toh",
  "And ho ske toh mere saath bhi ruk Jana",
  "Just in case rata ko koi issue hua toh",
  "<Media omitted>",
  "<Media omitted>",
  "Thakur uhjhhwal aur devesh",
  "<Media omitted>",
  "<Media omitted>",
  "Okay",
  "<Media omitted>",
  "Wase ek baat toh h",
  "Hmare hostel se sunder female energy yha pr hain aur saath bhi",
  "<Media omitted>",
  "@⁨Rahul Singh New⁩ ho ske toh aajaiyo saare bhai fun krenge aur kartik ko kal ki galti ke liye gandi gandi galiya denge",
  "One more thing raat ko Terris pr Mt Jana .... Girls rehti h wha toh yeh buddhi mna kr rhi thi",
  "Yeh bkl piche pad gye ki hum aae hamara khana peena krwa",
  "Machhar bahut h uske liye kuch agarbatti wagarh aur machis ki dabbi",
  ".",
  "Smjh girls rehti h waha",
  "😁",
  "Pta nhi",
  "Aaj pta krunga",
  "Haan",
  "<Media omitted>",
  "Bhai woh video bhej de",
  "<Media omitted>",
  "This message was deleted",
  "<Media omitted>",
  "<Media omitted>",
  "Chauhan jo tu iske saath krne ki keh rha tha aur m mna kr gya tha ki rehne de woh kr diyo execute!!!...\n\nKartik tu isi layak hain!",
  "@⁨Rahul Singh New⁩ .....hmari sandook se mkc 3.0 ki script nikal le",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "Okay main apne elite club me experiment kr rha tha kartik ki personality ko leke ...\n\nAur isne uss experiment ka result positive dikhaya hain!!",
  "Ki dekh yeh maa behen pr uttega",
  "😂😂🤣🤣☠️",
  "Yeh bhi done ho gya experiment ...\n\n@⁨Rahul Singh New⁩ video ka content mil rha h!",
  "Thik hain bhai",
  "Maa tk pahucha toh tu tha pr",
  "Elite club me Kartik ki personality decode kr rhe hai ..\n\nAnd the conclusion was... Kafi insecure and fragile ego hain ....",
  "POLL:\nKal chalna hain?\nOPTION: Haan (1 vote)\nOPTION: Naa (2 votes)",
  "https://youtu.be/6X-SG6bA4Zg?feature=shared",
  "<Media omitted>",
  "Mtlb Hume kal chalna hain?",
  "<Media omitted>",
  "<Media omitted>",
  ".",
  "Muthi lga fatafat ..... Virya tere sar Chad gya hain....\n\n\nBkl bss bheed dikhani h... That's it ... Placement ke liye woh wase bhi nhi aaenge",
  "Kya kr lenge bol denge faridabad se kase aate sir thand bhi h asi cheeze aap log hafte bhar pehle btaya kro",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "Mt aa keshav",
  "Bahi sun baat dosti ki hain sirf dosti ki toh m abhi aajau",
  "But baat itni si hain wha kuch imp nhi hain!",
  "Aur subha subha pareshaan ho jaenge na kuch packing ki hain!",
  "Tu yeh Mt bol please ki dosti kr ke galti krdi bura lga gya mujhe!",
  "@⁨Harsh Fbd EE⁩ @⁨Rahul Singh New⁩ \n\n\nThe only reason kal nhi aara is ki koi zarurat nhi hain.... Rhi baat diwali mela ki woh matra ek regret h uss se zyada kuch nhi ...\n\nTum dono please ase Mt kro!",
  "https://youtu.be/_IT7_zyw0ro?feature=shared",
  "Kya hum kettle lene wale hain?",
  "Lelo!!",
  "Okay",
  "if(food!= Non-Veg){\n      Sout(\"I am in\");\n} else{\n      Sout(\"I am out\");\n}",
  "gas bharwane ka kaam badh jaega khair bhwaani toh ek hi bar hogi aur bill bhi km aaega economically and by use dekhe toh Rahul ki choice better hain",
  "but chodo ... Kartik ne mna kr diya hain wase bhi toh discussion ka koi point nhi hian",
  "yeh pura cylinder kitne din chal jaega",
  "<Media omitted>",
  "https://www.instagram.com/reel/DCjEkqSy6Pa/?igsh=MTJsNXIxcjQ3c2Q1aQ==",
  "This message was deleted",
  "Nhi yaar",
  "Woh ganda ganda bolta h",
  "50 rs nhi diye toh pregnant kr diya",
  "Bss toh meri choice h ki main nhi kahunga kyuki ande me semen milane se kuch nhi hoga but uss unfertilized egg se chances the ....",
  "Tu ase hi hua tha",
  "?",
  "<Media omitted>",
  "Ander ki khabar hain ki 4 se practicals hain",
  "Krdiyo bhai",
  "7206504070",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "Just read your notes they are more then enough",
  "Bsdk",
  "Yeh bhi nhi gya h!",
  "<Media omitted>",
  "<Media omitted>",
  "Happy new year 🎊🎉 homies",
  "🥹🥹",
  "<Media omitted>",
  "<Media omitted>",
  "Electricity bill payment done ✅",
  "<Media omitted>",
  "@⁨Kartik Cse⁩ haan Bhai?",
  "POLL:\n27 ko bus paas\nOPTION: Yes (2 votes)\nOPTION: Mkc (0 votes)",
  "🧿🧿",
  "Please",
  "<Media omitted>",
  "Unlimited food 🥝",
  "@⁨Rahul Singh New⁩ are u ready?",
  "😂😂",
  "Himanshu tune yeh baat likhi kase teri approach kya thi?",
  "🤣🤣",
  "<Media omitted>",
  "<Media omitted>",
  "Yeh sb kya ho gya",
  "<Media omitted>",
  "<Media omitted>",
  "😭😭💔",
  "Sports meet me toh nhi jana",
  "Aur ... Varun bhai ke loss ka sirf khed hi kr skte h!",
  "Aur hum kr bhi kya krte hain!",
  "As per your say",
  "Bhai Mera recharge nhi hain aur m bank activate nhi kr paa rha",
  "Recharge kr diyo ...",
  "Sun kr hi rha hain na toh saal wala kr diyo",
  "Abhi nhi pta",
  "Abhi toh just team bna rhe",
  "<Media omitted>",
  "Photo toh kartik ki lga rakhi hain",
  "Story me",
  "How can we help ?",
  "Harsh can you please recharge my phone so that I can help him!",
  "Tune yeh phrase kha se seekha pehle yeh bta?",
  "<Media omitted>",
  "Khaas grp ke bande",
  "Bhai rahul mujhe bachale",
  "Inn bkl se",
  "https://youtube.com/shorts/EJyRCbNel0I?feature=shared",
  "Badhiya",
  "✅",
  "You home is awesome 😎",
  "Congratulations 🎉 Rahul!",
  "This message was deleted",
  "reddybook.live",
  "Ab maa ko sone ke kangan laakr dena",
  "Follow malik numbai",
  "<Media omitted>",
  "Yeh sb hme chalaava de rha hain",
  "Haan cse ki team pta kro yaar koi",
  "<Media omitted>",
  "Our dream 11",
  "4 bol me 11 run de diye",
  "Yeh kartikey toh nhi h?",
  "Mane toh ME pr hi satta lgaya tha",
  "Hana bhaiyo Krna h kya kuch?",
  "Loud ho",
  "Chodo yaar pase le rhe!",
  "Sb kuch inka wase scripted hota hain jita denge Shruti aur varun ko!",
  "Jo thode thik se hain unke anshu keshav chaat lenge",
  "🥹🥹",
  "Haan inki woh wali",
  "https://www.instagram.com/p/DGGDI27vJhb/?igsh=MWdjNjk5aGE0Y2FhNg==",
  "<Media omitted>",
  "<Media omitted>",
  "Thanks!! 😊",
  "<Media omitted>",
  "Duvidha naam h",
  "Suvidha",
  "*",
  "😂",
  "😂😂😂",
  "https://www.instagram.com/reel/DGc5bpzycm6/?igsh=MTVnNTFkdXd5eTZ6Zw==",
  "Rahul to his selected teams",
  "😂😂",
  "Saal me",
  "3 saal ka",
  "Homies ....\n\n17 march se sessional hain \n      --- thakur",
  "Comeback postpone Krna padega",
  "😂😂",
  "https://www.instagram.com/reel/DGcJRQ-Bmo5/?igsh=czl2amdrb3R0ZjBn",
  "<Media omitted>",
  "Bhaiyo lelo paas aaj woh bol rha tha ki 11 ko issue ho chuka ab yaad aayi h",
  "<Media omitted>",
  "Are yaar",
  "CSE suffix!! 😄",
  "⭐⭐⭐⭐⭐",
  "<Media omitted>",
  "<Media omitted>",
  "Happy Holi Homies 🎁🥳🎉",
  "🤣🤣",
  "Tune mere chauhan ki marne ki baat ki",
  "<Media omitted>",
  "Rangotsav ki hardik shubhkamnaye 🌺🌻",
  "Flaunting*",
  "Hahah",
  "The only way to escape matrix",
  "Aur mera khush",
  "Sbhi result btado",
  "Please patience rakhiye sir aapka hi withdrawal ho raha hai theek hai sir line by line  sabhi clients ka withdrawal ho Raha hai sir aap wait karenge approved hone tak.....\n\n\n🙏🙏 *Sorry for delay* 🙏🙏",
  "Chud gye",
  "Unique hain but acha or bura?",
  "Achaaa",
  "This message was deleted",
  "Kartik bhai ko koi kuch nhi bolega!",
  "@⁨Harsh Fbd EE⁩ bhai kamre ka kya Krna hain?",
  "<Media omitted>",
  "Tum log 10 over me 86 bnwao!",
  "Toh bhai usne yhi toh pucha tha",
  "😂😂",
  "Isme iske moo me mootne ki kya baat thi",
  "😂😂",
  "Toh tune isko isko maa ka bhosda kyu bola",
  "Dum h toh Modi se uski degree maang!",
  "Tu bc anti national pakistan chala ja",
  "Supreme leader h modi ji hmare",
  "Mazak mazak game palat jaega mere bhai!",
  "Bhai kal krte hain iss baare me baat",
  "@⁨Kartik Cse⁩ kamre ka kya Krna hain bhai kal Jana hain humko!",
  ".",
  "Bkl",
  "Kha h tu itni der se?",
  "🧿🧿 \n\nGhar se dur ek ghar ❌ \nKartik se dur ek Kartik ✅",
  "Aaj bc rajesh yadav ne bhi bol diya ki mood nhi h project lene ka Monday ko lunga",
  "This message was deleted",
  "This message was deleted",
  "This message was deleted",
  "This message was deleted",
  "This message was deleted",
  "Kha ho?",
  "<Media omitted>",
  "Nhi woh seminar me hogi",
  "🤣🤣",
  "Kartik tu saaf suthra tha ab nhi me mootwa rha",
  "Kya kha mkc ke member ho .....Are laao laao sir bag mujhe do!",
  "Iska ego hurt ho gya samne wale ne isko samne se issue bta diya toh",
  "Bhai meri galti nhi h match fixed hain",
  "2 over me 36 bn gye the",
  "<Media omitted>",
  "Hana super over chalra",
  "Dekhi jeet rhi",
  "Delhi*",
  "Jo mne kha tha",
  "🤣🤣",
  "<Media omitted>",
  "Likh likh harsh darr mt",
  "Haina?",
  "Kitan pyara lgra!",
  "Iski toh gaand pr laat marni padegi!",
  ".",
  "Hum iss se sirf kadhi lelenge aur bread ke saath kha lenge \n\n\nThese days are about to come 😭",
  "Haan",
  "@⁨Kartik Cse⁩",
  "Video bhejde",
  "Video bhejde",
  "@⁨Kartik Cse⁩",
  "@⁨Kartik Cse⁩ bta bhai!",
  "Krlenge baat;",
  "Atleast",
  "Whi OG 3",
  "You me and kartik!",
  "Bola tha na yes ke session hn",
  "New sting before exams",
  "Kartik OP!",
  "<Media omitted>",
  "tatha astu",
  "😃",
  "😭😭",
  "Laadli behna yojna ka budget bhi toh badhana hain!",
  "Kal sare bhai anil ke yha aajana kartik ka cake cut krnege",
  "😂😂",
  "Dear [PG Owner's Name],\n\nWe hope you are doing well. This is to inform you that Kartik and Keshav, tenants of Room No. 8 at Vansh PG, have vacated the room as of 14th June, completing our stay from 15th May to 14th June. We have left the room in the same clean and proper condition as it was when we moved in.\n\nWe would also like to confirm that we have paid the electricity bill in full. The meter reading started at 279 units and ended at 296 units, resulting in a total consumption of:\n\n296 - 279 = 17 units\n17 units × ₹8 = ₹136\n\nSo, we have paid ₹136 towards the electricity charges.\n\nAs our stay has officially ended, we kindly request you not to start the rent for the next month, and you may feel free to allot the room to a new tenant.\n\n\n---\n\nFeedback for Improvement:\n\nWe would also like to share a few suggestions that may help in improving the overall experience for future tenants:\n\n1. Visitors/Friends Policy: Tenants should be allowed to invite their friends without restrictions for casual meetups.\n\n\n2. Freedom for Enjoyment: Light fun and conversations in a louder voice should be allowed, especially during reasonable hours.\n\n\n3. 24×7 Electricity & Wi-Fi: Consistent electricity and internet availability is essential for study and work purposes.\n\n\n4. Water Cooler Safety: The water cooler was giving electric shocks – it needs urgent maintenance for safety.\n\n\n5. Judgemental Environment: Some neighbours seemed to judge us based on dressing sense, which affected our sense of freedom and comfort.\n\n\n6. Air Conditioning: Installing an AC would greatly enhance comfort during peak summer.\n\n\n\nWe hope this feedback will be taken positively and help in improving the PG environment for everyone. Thank you for your support during our stay.\n\nBest regards,\nKartik & Keshav",
  "Hello [PG Owner's Name],\n\nYeh batane ke liye message kar rahe hain ki Room No. 8 (tenants: Kartik aur Keshav) humne 14th June ko vacate kar diya hai. Humne 15th May se 14th June tak yahan stay kiya.\n\nRoom ko waise hi clean aur proper condition mein chhoda hai jaisa humein mila tha, aur saare dues bhi clear kar diye hain.\n\nElectricity bill ka breakdown:\nMeter reading: 279 to 296 = 17 units\nPer unit rate: ₹8\nTotal: 17 × 8 = ₹136\nHumne ₹136 ka bill pay kar diya hai.\n\nToh kindly next month ka rent start na karein. Ab aap room kisi naye interested person ko allot kar sakte hain.\n\n\n---\n\nKuch feedback dena chahenge, jo future mein PG ke liye helpful ho sakta hai:\n\n1. Friends ko PG mein aane ki permission honi chahiye.\n\n\n2. Thoda loud mein baat ya masti allowed honi chahiye, jab tak disturbance nahi ho.\n\n\n3. Electricity aur Wi-Fi 24×7 available rehna chahiye.\n\n\n4. Water cooler mein current aa raha tha — please check karwa lijiye, thoda unsafe tha.\n\n\n5. Kuch neighbours humein dressing sense ke basis par judge karte the, jo thoda uncomfortable feel hua.\n\n\n6. AC install ho jaaye toh summer mein kaafi better comfort milega.\n\n\n\nHope aap is feedback ko positively lenge. Thank you for your support during our stay 🙏\n\n- Kartik & Keshav",
  "🥲",
  "Bkl m",
  "😭😭",
  "Teri maa ki chut Randi ke",
  "Chauhan iss kutte ki maa chod de",
  "Bc mere bagal wale ne dekhli!",
  "Merko itne gande tareeke se dekhra h woh 😭😭",
  "@⁨Kartik Cse⁩ kutte tere ghar me behen beti ho unko bhej",
  "Kya kru m iska chauhan.",
  "Yeh kisi grp me rakhne layak nhi h yeh kuttema",
  "Hmne apne aura ko sankat me daal kr isko rakha",
  "Ab ho gyi galti!",
  "Whi toh par kis ki!",
  "Teri job toh nahi chali gayi \nIse betichod ke karan",
  "Radi ka",
  "@⁨Kartik Cse⁩ ab pase bhejde",
  "Sb bolo bhai isko pase bhejne ki",
  "<Media omitted>",
  "Bhaag jau leke?",
  "<Media omitted>",
  "Job ke liye aapko 100 rs bhejne padenge taki hm aapka verification kr ske",
  "Nhi sir yeh aapke account verification ke liye h!",
  "<Media omitted>",
  "Haath nhi kaanpe type krte hu?",
  "Hue*",
  "Ekbaar ko kisi ne dekh liya na toh porn ke liye maaf kr dega",
  "@⁨Rahul Singh New⁩ iss kutte ki chamdi masala maang rhi h",
  "Konsi harkat?",
  "Apni biwi toh nhi chudwa rha!",
  "<Media omitted>",
  "Kutte bol",
  "Krdu kalyaan?",
  "Bohonchod du inkin",
  "😂",
  "@⁨Rahul Singh New⁩ I have a theory jb ki kisiko hmari class me public opinion Lena hota h toh woh shivam se contact krta h",
  "Toh Krle bhai",
  "Yeh meri wali h",
  "<Media omitted>",
  "Yeh ho gya toh m khana khane baith gya lunch break se pehle hi",
  "Aur special ops chala li",
  "Bkl ne record kr ke status daal diya",
  "GenZ in office",
  "Tera toh koi bhai bhi nhi h",
  "@⁨Kartik Cse⁩",
  "Apne lgenge kugte",
  "Pr hug hmesha tujhe bhai hi bole ge",
  "Exactly 💯",
  "<Media omitted>",
  ".",
  "<Media omitted>",
  "https://www.instagram.com/reel/DMkx1D4RCto/?igsh=MW9hcGc4cjRnbDhvOQ==",
  "Main bhraman hu m baithunga",
  "Bss kr mote bss kr",
  "You are being looked by alpha coder",
  "<Media omitted>",
  "🥺",
  "<Media omitted>",
  "@⁨Rahul Singh New⁩ conspiracy bta",
  "Bkl train me hu m",
  "🙃",
  "Kutte tujhe tameez kyu nhi h!",
  "Shabaash!",
  "Baniya ekta group  me bhej",
  "Nhi toh beta tera phone haath aane de",
  "Yehi performance denge",
  "Minor lgri rhne dete h",
  "😂😂",
  "https://youtu.be/vtG4lGJ2lig?si=EmcEGFqZ3OE8xMJj",
  "For harsh",
  "Electrical h tu cup hoja",
  "For kartik bhai",
  "😘",
  "Kya hil hil k chummi gyi h bc",
  "Harsh bhai ghar tk mt jaa",
  "Kartik toh nhi gya",
  "Haan yaar harsh tu bhi bol",
  "Oee",
  "Aukaat me rehle",
  "Haan 10 bje tk rani h",
  "Aage ka system @⁨Kartik Cse⁩ bhai btaenge",
  "Bhai harsh ase nhi hota",
  "Comebsck issi saal karwane ka?",
  "Done ✅",
  "Are ek ayushi me re dedi thi",
  "Yeh sb kuch itna acha hora kuch galat hone wale h kya?",
  "@⁨Rahul Singh New⁩",
  "Bhai m ignore kr rha hu tujhe smjh nhi aara?",
  "Modi raaj me hi sb changa si h!",
  "Tu toh h hi banrakas",
  "Saala vidhayak(rahul gandhi) ki gaand me ghus jaa",
  "Bhai Modi ji ne kiya h soch smjh kr hi kiya hoga",
  "👅😛",
  "😋🤤",
  "Mote sb shi hora h life m",
  "Yeh sb mt kr",
  "From khel khtam h toh comeback",
  "<Media omitted>",
  "Iske zimmedari leli gyi h!",
  "Aap lelo",
  "Goli chal gyi",
  "<Media omitted>",
  "@⁨Kartik Cse⁩",
  "Kaash m just paas ka use krta misuse nhi ab dekho naseeb bhi nhi jo paega",
  "Ab shuru hogi panchyat level politics",
  "Kahin vighnesh goli na matwale khudko election jitne ke loye",
  "Kon anuj?",
  "Tune bola kya?",
  "Usko ki cooler lele!",
  "Kon h yeh anuja?",
  "Acha",
  "Woh kya",
  "...",
  "Hana kartik bhai!",
  "❤️",
  ".",
  ".",
  "https://www.instagram.com/reel/DNvjsDhwiqv/?igsh=eTVsaHNleG1sMGc5",
  "Me",
  "Jaggu ka number please",
  "🥺🥺",
  "Isko bulaya hi kyu!",
  "@⁨Kartik Cse⁩",
  "<Media omitted>",
  "🥺",
  "Yeh google kitna chutiya hain btao hum jaso ko pro dediya 1 saal ka free ka bhai iske jaisi chutiya company nhi dekhi",
  "🌻🐻‍❄️",
  "We*",
  "<Media omitted>",
  "Ab hogi ahmedabad buses k saath whi jo haryana roadways ke saath hua tha",
  "Hmne pase milae the?",
  "Hain hi sala scammer",
  "Shakal dekh kr day 1 pr lg gya tha",
  "<Media omitted>",
  "😂😂",
  "😂",
  "Zeb me ched ho jae toh pase se pehle rishte gir jaate hain \n\nBaat gehri h phirse padhna",
  "Haayeee",
  "<Media omitted>",
  "<Media omitted>",
  "Exactly",
  "Main dkeh hi rha tha ki kon observe kr pata h",
  "Haryanvi sun iski",
  "Lakshay Chaudhary inke upar hi bnata h reels",
  "@⁨Harsh Fbd EE⁩",
  "<Media omitted>",
  "🙂🙂",
  "<Media omitted>",
  "🥺🥺",
  "Happy Diwali homies!!",
  "Chup hoja mote",
  "Freeze lgwa denge saare hindu sher milkr",
  "Kyu bhai harsh!",
  "@⁨Harsh Fbd ",
  "Hana chal pase bhej de",
  "Tu chuo reh",
  "Mulle",
  "Katue",
  "Pakistan chala jaa",
  "Haan",
  "Bhai full stack h apna !",
  "With AI and block chain!",
  "What's new",
  "<Media omitted>",
  "Are bhai",
  "https://music.youtube.com/watch?v=csKv7M1Jxxg&si=vNOvEYDv2NKDadXH",
  "0:55",
  "Mutthi done NNN begins",
  "😂",
  "<Media omitted>",
  "Piche amarjeet tha",
  "https://www.instagram.com/reel/DQqOJxhkyQa/?igsh=bGxwdzlrZGo4cDdw",
  "Kal yha patakhe phode h",
  "147 h yha",
  "<Media omitted>",
  "Meri 3 meal se bhi xyada calories h!",
  "Ok",
  "Mote mar jaega",
  "Then don't",
  "Main resign kr dunga",
  "2sra hmesha oothunga",
  "<Media omitted>",
  "My love",
  "Kutte Ka din aagya",
  "This message was deleted",
  "😂😂",
  "Ab toh padhle",
  "Nhi jana",
  "😂😂",
  "<Media omitted>",
  "Ahmedabad me h!.",
  "13k",
  "Mil jaega",
  "3500 without bed",
  "4000 with bed",
  "thik hian kafi kamre hain",
  "main kehra",
  "11 tk ruk jao",
  "phir next 11 tk rhega apne paas",
  "11 ko saare bhai chalenge",
  "yeh chauhan hota na",
  "pakka pareshaan krta",
  "bata hi nhi ki",
  "bol denge 1 hafte ki baat h tang mt kr",
  "yeh kya hain?",
  "tu krle",
  "na",
  "Krta hu",
  "Nhi h",
  "Khud dukaan me reh tha g",
  "Rha h",
  "Wohhoooo",
  "Tbhi phone nhi oothaya mera",
  "Kal chale yeh project report bhi dedenge",
  "Aur",
  "Seedhe kamre me chalte hain",
  "Ok",
  "Whensoever you go to recieve your admit card... \nHave your adhar card no. \nAnd all semester cgpa with you for verification. \n\nWhen once verified then only admit card will be given to you.",
  "Kutte tera aadhar bhejde",
  "Sakshi ko",
  "Tmkc",
  ".",
  "Lazer show h!",
  "<Media omitted>",
  "<Media omitted>",
  "This message was deleted",
  "https://www.youtube.com/live/WdgEeFA7cm0?si=6PHclnx8tjZjnbAD",
  "https://youtube.com/shorts/q2Iqy05UMNM?si=fWN1ASzlGi9_Fbfl",
  "Pehli baar re ka exam dene aagys",
  "Kal adjust krwani hain yaad rkahna",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "https://www.instagram.com/reel/DSm5qPODxGW/?igsh=MWNzcjFwODZjYTV3dw==",
  "Byeee homies love you",
  "<Media omitted>",
  "This message was deleted",
  "🧿",
  "@Harsh Fbd  Happy Birthday",
  "Phoolon ne amrit ka jaam bheja hai\nSooraj ne gagan se salaam bheja hai\nMubarak ho aapko naya janmdin\nTahe-dil se humne ye paigaam bheja hai",
  "<Media omitted>",
  "<Media omitted>",
  "😂😂",
  "Happy new year homies",
  "❌❌ rahul ka phn chori ho gya h",
  "<Media omitted>",
  "<Media omitted>",
  "Bus + sun + tea == Basanti",
  "https://www.instagram.com/reel/DTatNpFDKO6/?igsh=aWFxNzF3bnhmZXBo",
  "Bhai koi jaggah ho nhi h!",
  "M toh sochra yadav dharamshala ruk jate hain",
  "Nhi h chod diya",
  "Nhi",
  "Hn jhajjar m toh fog hi j",
  "Tu marega",
  "Haan haan",
  "<Media omitted>",
  "Konsi site?",
  "Thik h",
  "Abhi jata hub",
  "Match ke hisaab se dekhle",
  "Pase ki need h hain toh rhne de",
  "Fun Krna h toh khel le",
  "Bss bahut h aaj ke liye",
  "Ab yeh esa match hi higa ki",
  "Punters haare",
  "Matvh kiska h",
  "Kaha h!",
  "Woh bta diyo",
  "Yeh khel liyo",
  "Yes ke session aaenge",
  "Aaj kuch mt kr",
  "If you fin the first trade call it done for the day",
  "Krte h",
  "Acha 5 log h kya hum",
  "M socha 4 hain",
  "😂",
  "Rage bait?",
  "Hotel toh nhi chaiye ga kyu bhai Rahul",
  "Aaj toh profit ke peso swere laad leee laaadleee",
  "Ohh bhaiaiaiaiia",
  "😂😂",
  "😂",
  "Ok",
  "😂😂",
  "Still 5 ka hi rate?",
  "Abhi kya rate aara?",
  "Chod chalne de",
  "Ab kuch mt kr",
  "😂😂",
  "Happy holi homiessss",
  "<Media omitted>",
  "😂😂",
  "<Media omitted>",
  "Without once bhejiyo",
  "😂😂😂",
  "<Media omitted>",
  "Naaachoooooo",
  "All clear",
  "<Media omitted>",
  "<Media omitted>",
  "…..",
  "Yeh story lga de?",
  "Chalo vai",
  "M Ahmedabad se aajau ga",
  "Tera sat sun off h?",
  "Thik h",
  "Bta do bhai abhi merko tockets krni padti h",
  "Done h bhai mane train bhi dkehlinj",
  "Dekhli h",
  "This message was deleted",
  "Love you homies 😩😩",
  "💕",
  "https://www.instagram.com/reel/DWI15QhDijD/?igsh=MWpiaTN5NHpvN2JsMg==",
  "<Media omitted>",
  "Monday ko hoga",
  "Baniyo ki shadi",
  "Acha",
  "Usme nora fatehi aaegi",
  "<Media omitted>",
  "<Media omitted>",
  "Job openings",
  "<Media omitted>",
  "😂",
  "<Media omitted>",
  "Isme toh bahut kharcha ho hya higa",
  "💦💦",
  "Toh ghar le aau terko?",
  "Kitne ki aati h?",
  "Enjoy 😉",
  "Check your bank statements",
  "Tu condom nhi lund ho mera",
  "One and only",
  "Ijjat hi nhi achi lgti",
  "<Media omitted>",
  "Unit Wise PYQs hain",
  "Chandigarh?",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "<Media omitted>",
  "Acha",
  "Tu toh phir bhi chalagya",
  "<Media omitted>",
  "<Media omitted>",
  "Khalu?"
]